---
title: "Instacart Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(p8105.datasets)
library(plotly)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
instacart %>% 
   group_by(aisle) %>% 
   summarize(n = n()) %>%
   filter(n > 10000) %>%
   plot_ly(x = ~aisle, 
           y = ~n, 
          type = "bar") %>% 
   layout(title = 'Number of Products Ordered by Aisle',
          xaxis = list(title = "Aisle"), 
          yaxis = list(title = "Number of Products Ordered"), 
          showlegend = FALSE)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
instacart %>% 
  filter(add_to_cart_order <= 15) %>%
  sample_n(300) %>%
  mutate(reordered = as.factor(reordered)) %>%
  plot_ly(x = ~days_since_prior_order, 
           y = ~add_to_cart_order,
          color = ~reordered,
          type = "scatter", 
          alpha = 0.5) %>% 
   layout(title = 'Relationship between order of item addition to cart and time elapsed since last order',
          xaxis = list(title = "Days since the last order"), 
          yaxis = list(title = "Order of item addition to cart"), 
          showlegend = FALSE)
```

### Chart C

```{r}
instacart %>% 
  filter(aisle %in% c("frozen vegan vegetarian", "frozen appetizers sides",
                      "frozen breakfast", "frozen meals", "frozen dessert", 
                      "frozen pizza")) %>%
   mutate(aisle = fct_reorder(aisle, order_hour_of_day)) %>%
   plot_ly(x = ~aisle, 
           y = ~order_hour_of_day,
           color = ~aisle,
          type = "box") %>% 
   layout(title = 'Distribution of Time of Order Placement for Frozen Food',
          xaxis = list(title = "Frozen Aisles"), 
          yaxis = list(title = "Hour of Order Placement"), 
          showlegend = FALSE)
```

